kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spat-traefik-role-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spat-traefik-role
subjects:
  - kind: ServiceAccount
    name: spat-account
    namespace: default
    